### ISSUE TITLE
Visitors Browser and OS Breakdown Component

### ISSUE THREAD

**Issue by alexmcdermid** [harled/matey#67]
Will display visitors browser and os in a table.

Method signature will likely include:

- visits: the ahoy visit data
- time_window: the time window of visit data

**Comment by alexmcdermid** [comment]
Can't seem to assign myself or create a branch, maybe a permissions issue.

**Comment by krsyoung** [comment]
@alexmcdermid best workflow is to fork the project to your account, then branch and PR from there. 

Let me know if it isn't cooperating.  Here is an article with a lot more detail about [Fork, Branch and PR](https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/)

**Comment by alexmcdermid** [comment]
here's the branch from the fork: https://github.com/alexmcdermid/matey/tree/browserOsBreakdownComponent

Still working on a few things

**Comment by krsyoung** [comment]
Looking really good @alexmcdermid! I can't comment on the specific lines of code (in this case because it is in your fork!) but one tip to consider that should give some major performance improvements:

```
# in ruby land (slow)
visits.each{ |visit| browsers.key?(visit.browser) ? browsers[visit.browser] += 1 : browsers[visit.browser] = 1 }

# in database land (fast)
visits.group(:browser).count
```

Something like the above will use the database group function to do the group and aggregate summation for you.  Same deal for the OS reporting.

**Comment by alexmcdermid** [comment]
Thank you @krsyoung

I'll implement those changes.  I left a comment about needing to query the database differently (I knew I was just tallying in a loop), but I wasn't sure exactly how to before seeing this.
